title: SoloID Authenticator
theme: just-the-docs

url: https://signaturgruppen-a-s.github.io/soloid-authenticator-documentation
logo: "/assets/broker-logo.png"
favicon_ico: "/assets/favicon.ico"

aux_links:
  GitHub repository: https://github.com/Signaturgruppen-A-S/soloid-authenticator-documentation
