title: SoloID Authenticator documentation
description: SoloID Authenticator documentation.
theme: just-the-docs

url: https://signaturgruppen-a-s.github.io/soloid-authenticator-documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
